### PR TITLE
Add readme and hardware design guide

### PR DESCRIPTION
**Pull request by robpl4788**

### CODE REVIEW

**Comment by VitroidFPV** [comment]
Why was tested-targets.md removed? I understand that it's currently empty but the base format should be kept for actual future additions

**Comment by robpl4788** [comment]
> Why was `tested-targets.md` removed? I understand that it's currently empty but the base format should be kept for actual future additions

I removed it because to me, even if it had content, it's currently redundant because of `list-of-supported-hardware.md`, which seems to serve the same function. Plus it seems super weird to me to have an empty page on live documentation

**Comment by VitroidFPV** [comment]
It's meant to follow the same format as the discord channel, to hopefully get that data off a social platform to a proper doc page.

If you leave it in, the rest of the PR looks good - I'll fill it out with the discord info this week

**Comment by robpl4788** [comment]
i still don't understand how it is different to `list of supported hardware.md` but i have restored the file

**Pull request merged**
